#!/usr/bin/python3
class Rectangle:
    def __init__(self, width=0, height=0):
        self._width = width
        self._height = height
        
        
        def width(self, value):
            if not isinstance(value, int):
                raise TypeError("width must be an integer")
            elif value < 0:
                raise ValueError("width must be >= 0")
            self._width = width
            
        def width(self, value):
              if not isinstance(value, int):
                  raise TypeError("height must be an integer")
              elif value < 0:
                  raise ValueError("height must be >= 0")
              self._height = height
        
        
 
